In [2]:
import itertools
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('car_data.csv')
df.head()

buying  maint  doors  persons  lug_boot  safety  class_value
0       3      3      2        2         0       0            0
1       3      3      2        2         0       1            0
2       3      3      2        2         0       2            0
3       3      3      2        2         1       0            0
4       3      3      2        2         1       1            0

verileri görüntüledik şimdi önhazırlık yapacağız

In [4]:
df['class_value'].value_counts()

class_value
0    1210
1     384
2      69
3      65
Name: count, dtype: int64

In [5]:
df.columns

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety',
       'class_value'],
      dtype='object')

datasette bulunan features

In [6]:
#class value haricinde numpy array oluşturma
X = df[['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety']].values
X[0:3] # ekrana yazılan veri sayısı

array([[3, 3, 2, 2, 0, 0],
       [3, 3, 2, 2, 0, 1],
       [3, 3, 2, 2, 0, 2]], dtype=int64)

'buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety' sütunlarını X olarak tanımladık

In [7]:
y= df['class_value'].values
y[0:5]

array([0, 0, 0, 0, 0], dtype=int64)

ilk 5 değerimiz 0 

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3, random_state=3) #veri setinin yüzde 30u test yüzde 70i eğitim için kullanılacaktır

In [17]:
print("X_train boyut:", X_train.shape, "y_train boyut:", y_train.shape)
print("X_test boyut:", X_test.shape, "y_test boyut:", y_test.shape)

X_train boyut: (1209, 6) y_train boyut: (1209,)
X_test boyut: (519, 6) y_test boyut: (519,)


ilk olarak Class_Value isminde bir DesicionTreeClassifier öğrneği oluşturacağız 

In [18]:
Class_Value = DecisionTreeClassifier(criterion="entropy", max_depth = 4)
Class_Value

DecisionTreeClassifier(criterion='entropy', max_depth=4)

modeli eğitime geçelim

In [19]:
Class_Value.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=4)

tahmin ve değerlendirme

In [20]:
Class_Value_predict = Class_Value.predict(X_test)

In [21]:
Class_Value_predict[0:5]

array([1, 0, 0, 1, 2], dtype=int64)

Class_Value_predict yapmış oluğu ilk 5 değer için tahminler
şimdi bütün veriseti üzerindeki başarı oranına bakalım

In [22]:
from sklearn import metrics

In [23]:
print("DecisionTreeClassifier accuracy:", metrics.accuracy_score(y_test,Class_Value_predict))

DecisionTreeClassifier accuracy: 0.8131021194605009


Eğittiğimiz modelin başarı oranı %81 çıktı